### PR TITLE
Adding info, how to run a specific version of Docker

### PR DESCRIPTION
**Pull request by vogella**
# Important Notice

Patch submission and review is done through [Gerrit Code Review](https://gerrit-review.googlesource.com).
Unfortunately we cannot pull your code as a Pull Request.

__NO REVIEWS OR DISCUSSIONS will happen on GitHub__, all the code collaboration
will take place on Gerrit.

### CODE REVIEW

**Comment by lucamilanesio** [comment]
Thanks for your contribution. I've created the Gerrit change for you at https://gerrit-review.googlesource.com/c/docker-gerrit/+/271232

We will continue the review and the merge on gerrit-review.googlesource.com, hence I'll close this PR for now.

**Comment by vogella** [comment]
Thanks @lucamilanesio I was surprised that Docker image for Gerrit uses PR but that clarifies it.

**Comment by lucamilanesio** [comment]
@vogella could you register to gerrit-review.googlesource.com and sign the CLA? That would allow us to be able to legally merge your contribution (https://gerrit-review.googlesource.com/c/docker-gerrit/+/271232).

**Comment by lucamilanesio** [comment]
Ping @vogella did you check if you are willing to sign the CLA for your contribution?

**Comment by vogella** [comment]
image

Should be done now

**Pull request closed without merging**
